# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vmms', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Client name')),
                ('api_key', models.CharField(max_length=64, verbose_name='API key')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmms.Client')),
            ],
        ),
    ]
