# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0003_auto_20161112_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=128, verbose_name=b'Filter field')),
                ('word', models.CharField(max_length=32, verbose_name=b'Filter word')),
                ('value', models.CharField(max_length=256, verbose_name=b'Filter value')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'Folder name')),
            ],
        ),
    ]
