# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0004_playlistfilter_playlistfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'Playlist name')),
                ('genres', models.TextField(verbose_name=b'Genre IDs')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='vmms.PlaylistFolder')),
            ],
        ),
        migrations.AddField(
            model_name='playlistfilter',
            name='playlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='vmms.Playlist'),
            preserve_default=False,
        ),
    ]
