# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0005_auto_20161112_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='genres',
            field=models.TextField(blank=True, verbose_name=b'Genre IDs'),
        ),
    ]
