# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0006_auto_20161112_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'Event name')),
                ('start', models.DateTimeField(verbose_name=b'Start time')),
                ('end', models.DateTimeField(verbose_name=b'End time')),
                ('repeating', models.CharField(choices=[(b'DAY', b'Daily'), (b'WEEK', b'Weekly'), (b'MONTH', b'Monthly')], max_length=6, verbose_name=b'Repeating mode')),
                ('high_priority', models.BooleanField(default=False, verbose_name=b'Is this a high priority event?')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vmms.Playlist')),
            ],
        ),
    ]
