# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vmms.Client'),
            preserve_default=False,
        ),
    ]
