# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0009_event_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default=None, max_length=7, verbose_name=b'Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='repeating',
            field=models.CharField(choices=[(b'NO', b'Not repeating'), (b'DAY', b'Daily'), (b'WEEK', b'Weekly'), (b'MONTH', b'Monthly')], max_length=6, verbose_name=b'Repeating mode'),
        ),
    ]
