# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0010_auto_20161201_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Category name')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ExternalGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Genre name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmms.ExternalCategory')),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Program name')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Folder name')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(verbose_name='Playlist percentage in the program')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='high_priority',
            field=models.BooleanField(default=False, verbose_name='Is this a high priority event?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeating',
            field=models.CharField(choices=[('NO', 'Not repeating'), ('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly')], max_length=6, verbose_name='Repeating mode'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Genre name'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='genres',
            field=models.TextField(blank=True, verbose_name='Genre IDs'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Playlist name'),
        ),
        migrations.AlterField(
            model_name='playlistfilter',
            name='field',
            field=models.CharField(max_length=128, verbose_name='Filter field'),
        ),
        migrations.AlterField(
            model_name='playlistfilter',
            name='value',
            field=models.CharField(max_length=256, verbose_name='Filter value'),
        ),
        migrations.AlterField(
            model_name='playlistfilter',
            name='word',
            field=models.CharField(max_length=32, verbose_name='Filter word'),
        ),
        migrations.AlterField(
            model_name='playlistfolder',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Folder name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('User', 'User')], max_length=64, verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='programplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='vmms.Playlist'),
        ),
        migrations.AddField(
            model_name='program',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='vmms.ProgramFolder'),
        ),
    ]
