# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0011_auto_20170116_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='programplaylist',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='vmms.Program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmms.Playlist'),
        ),
    ]
