# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0012_auto_20170118_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmms.Playlist')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmms.Program')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='playlist',
        ),
        migrations.AddField(
            model_name='client',
            name='basic_content',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='vmms.Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vmms.Content'),
            preserve_default=False,
        ),
    ]
