# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 18:20
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('vmms', '0013_auto_20170120_1607'),
    ]

    operations = [

    ]
