# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0014_auto_20170125_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
