# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0016_playerversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerversion',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Is this version current?'),
        ),
    ]
