# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0017_playerversion_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
