# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0018_auto_20170201_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmms.Client')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmms.Content')),
            ],
        ),
    ]
