# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0019_clientcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='vmms.Client'),
        ),
    ]
