# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0020_auto_20170207_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('User', 'User')], max_length=256, verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
