# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-26 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0022_externalsong_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='content_mode',
            field=models.IntegerField(default=0, verbose_name='Content mode'),
        ),
    ]
