# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0023_playlist_content_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=128, verbose_name='Filter field')),
                ('word', models.CharField(max_length=32, verbose_name='Filter word')),
                ('value', models.CharField(max_length=256, verbose_name='Filter value')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='vmms.Client')),
            ],
        ),
    ]
