# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0024_clientfilter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfilter',
            old_name='playlist',
            new_name='client',
        ),
    ]
