# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0025_auto_20170228_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Tag name')),
            ],
            options={
                'db_table': 'songs_tags',
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tags',
            field=models.TextField(blank=True, verbose_name='Tag IDs'),
        ),
    ]
