# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0026_auto_20170301_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tags',
        ),
        migrations.AddField(
            model_name='playlist',
            name='exclude_tags',
            field=models.TextField(blank=True, verbose_name='Exclude tag IDs'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='include_tags',
            field=models.TextField(blank=True, verbose_name='Include tag IDs'),
        ),
    ]
