# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0027_auto_20170303_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsong',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
