# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0028_externalsong_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.CharField(max_length=1024, null=True, verbose_name='Playlist cover'),
        ),
        migrations.AddField(
            model_name='program',
            name='cover',
            field=models.CharField(max_length=1024, null=True, verbose_name='Program cover'),
        ),
    ]
