# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:54
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0029_auto_20170308_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='management', max_length=512, verbose_name='Website hostname where the user is active'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
