# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 09:52
from __future__ import unicode_literals

from django.db import migrations


def forward_func(apps, schema_editor):
    Client = apps.get_model('vmms', 'Client')
    for c in Client.objects.all():
        c.parent = None
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0030_auto_20170315_1454'),
    ]

    operations = [
        migrations.RunPython(forward_func)
    ]
