# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0031_flatten_all_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Folder name')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='vmms.ClientFolder'),
        ),
    ]
