# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:01
from __future__ import unicode_literals

from django.db import migrations


def forward_func(apps, schema_editor):
    ClientFolder = apps.get_model('vmms', 'ClientFolder')
    default_folder = ClientFolder.objects.create(name='Default')
    Client = apps.get_model('vmms', 'Client')
    for c in Client.objects.all():
        c.parent = default_folder
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0032_auto_20170316_1100'),
    ]

    operations = [
        migrations.RunPython(forward_func)
    ]
