# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0033_add_all_clients_to_default_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='vmms.ClientFolder'),
        ),
    ]
