# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0034_auto_20170316_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcategory',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalgenre',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
