# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0035_auto_20170321_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsong',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
