# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0036_auto_20170323_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
    ]
