# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0037_event_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsong',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
