# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0038_auto_20170329_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='secret_login_key',
            field=models.CharField(max_length=64, null=True, verbose_name='Secret login key'),
        ),
    ]
