# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 05:15
from __future__ import unicode_literals

from django.db import migrations
from vmms.utils import generate_secret_login_key


def forward_func(apps, schema_editor):
    Client = apps.get_model('vmms', 'Client')
    for c in Client.objects.all():
        c.secret_login_key = generate_secret_login_key()
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0039_client_secret_login_key'),
    ]

    operations = [
        migrations.RunPython(forward_func)
    ]
