# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0040_auto_20170406_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='secret_login_key',
            field=models.CharField(max_length=64, verbose_name='Secret login key'),
        ),
    ]
