# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0041_auto_20170406_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Promotion name')),
            ],
            options={
                'db_table': 'promotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_id', models.IntegerField(verbose_name='Promotion ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='vmms.Client')),
            ],
        ),
    ]
