# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0042_clientpromotion_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('playback', models.SmallIntegerField()),
                ('level_reduction', models.SmallIntegerField()),
                ('play_between_songs', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('order', models.IntegerField()),
                ('hash', models.CharField(max_length=36)),
                ('duration', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='ProgramPreviewLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Link name')),
                ('key', models.CharField(max_length=64, verbose_name='Secret key')),
                ('expiration_date', models.DateTimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmms.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='schedule', serialize=False, to='vmms.PromotionFull')),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTimes',
            fields=[
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='schedule_times', serialize=False, to='vmms.PromotionFull')),
                ('time', models.TimeField()),
                ('variance', models.SmallIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'schedule_times',
            },
        ),
    ]
