# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0044_auto_20170525_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time the request has been added')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_requests', to='vmms.Client')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='vmms.Content')),
            ],
        ),
    ]
