# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0046_clientfolder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistfolder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vmms.PlaylistFolder'),
        ),
        migrations.AddField(
            model_name='programfolder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vmms.ProgramFolder'),
        ),
    ]
