# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0047_auto_20170706_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Playlist notes'),
        ),
        migrations.AddField(
            model_name='program',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Playlist notes'),
        ),
    ]
