# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0048_auto_20170713_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='friday_close',
            field=models.TimeField(default=None, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='client',
            name='friday_enabled',
            field=models.BooleanField(default=False, verbose_name='Is client working'),
        ),
        migrations.AddField(
            model_name='client',
            name='friday_open',
            field=models.TimeField(default=None, null=True, verbose_name='Opening time'),
        ),
        migrations.AddField(
            model_name='client',
            name='monday_close',
            field=models.TimeField(default=None, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='client',
            name='monday_enabled',
            field=models.BooleanField(default=False, verbose_name='Is client working'),
        ),
        migrations.AddField(
            model_name='client',
            name='monday_open',
            field=models.TimeField(default=None, null=True, verbose_name='Opening time'),
        ),
        migrations.AddField(
            model_name='client',
            name='saturday_close',
            field=models.TimeField(default=None, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='client',
            name='saturday_enabled',
            field=models.BooleanField(default=False, verbose_name='Is client working'),
        ),
        migrations.AddField(
            model_name='client',
            name='saturday_open',
            field=models.TimeField(default=None, null=True, verbose_name='Opening time'),
        ),
        migrations.AddField(
            model_name='client',
            name='sunday_close',
            field=models.TimeField(default=None, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='client',
            name='sunday_enabled',
            field=models.BooleanField(default=False, verbose_name='Is client working'),
        ),
        migrations.AddField(
            model_name='client',
            name='sunday_open',
            field=models.TimeField(default=None, null=True, verbose_name='Opening time'),
        ),
        migrations.AddField(
            model_name='client',
            name='thursday_close',
            field=models.TimeField(default=None, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='client',
            name='thursday_enabled',
            field=models.BooleanField(default=False, verbose_name='Is client working'),
        ),
        migrations.AddField(
            model_name='client',
            name='thursday_open',
            field=models.TimeField(default=None, null=True, verbose_name='Opening time'),
        ),
        migrations.AddField(
            model_name='client',
            name='tuesday_close',
            field=models.TimeField(default=None, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='client',
            name='tuesday_enabled',
            field=models.BooleanField(default=False, verbose_name='Is client working'),
        ),
        migrations.AddField(
            model_name='client',
            name='tuesday_open',
            field=models.TimeField(default=None, null=True, verbose_name='Opening time'),
        ),
        migrations.AddField(
            model_name='client',
            name='wednesday_close',
            field=models.TimeField(default=None, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='client',
            name='wednesday_enabled',
            field=models.BooleanField(default=False, verbose_name='Is client working'),
        ),
        migrations.AddField(
            model_name='client',
            name='wednesday_open',
            field=models.TimeField(default=None, null=True, verbose_name='Opening time'),
        ),
    ]
