# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0049_auto_20170716_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField()),
                ('songs_count', models.IntegerField()),
                ('songs', models.TextField()),
            ],
        ),
    ]
