# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0050_cachedplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedplaylist',
            name='client_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
