# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0051_cachedplaylist_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedplaylist',
            name='songs_count',
        ),
    ]
