# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0052_remove_cachedplaylist_songs_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdatedAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=45)),
                ('last_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'last_updated_at',
            },
        ),
        migrations.AddField(
            model_name='cachedplaylist',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
