# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0053_auto_20170925_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='master_schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='Is master schedule enabled for client?'),
        ),
    ]
