# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 11:57
from __future__ import unicode_literals

from django.db import migrations
from vmms.utils import generate_api_key, generate_secret_login_key


def forward_func(apps, schema_editor):
    Content = apps.get_model('vmms', 'Content')
    ClientFolder = apps.get_model('vmms', 'ClientFolder')
    Client = apps.get_model('vmms', 'Client')
    
    basic_content = Content.objects.all().first()
    folder = ClientFolder.objects.all().first()

    master_schedule_client = Client(
        id=-1,
        name="Master Schedule Client",
        api_key=generate_api_key(),
        secret_login_key=generate_secret_login_key(),
        parent=folder,
        basic_content=None,
        master_schedule_enabled=False
    )
    master_schedule_client.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0054_client_master_schedule_enabled'),
    ]

    operations = [
        migrations.RunPython(forward_func)
    ]
