# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0055_auto_20171003_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Client group name')),
                ('clients', models.ManyToManyField(to='vmms.Client')),
            ],
        ),
    ]
