# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0056_clientgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Event name')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
                ('repeating', models.CharField(choices=[('NO', 'Not repeating'), ('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly')], max_length=6, verbose_name='Repeating mode')),
                ('high_priority', models.BooleanField(default=False, verbose_name='Is this a high priority event?')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmms.Content')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vmms.ClientGroup')),
            ],
        ),
    ]
