# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0057_groupevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeating_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Repeating end date'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='repeating_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Repeating end date'),
        ),
    ]
