# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0058_auto_20171109_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeat_every_n',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repeat every N weeks'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='repeat_every_n',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repeat every N weeks'),
        ),
    ]
