# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-01 20:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0059_auto_20171109_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVolumeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time the request has been added')),
                ('volume', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_requests', to='vmms.Client')),
            ],
        ),
    ]
