# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0060_clientvolumerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remote_volume_control_enabled',
            field=models.BooleanField(default=False, verbose_name='Is remote volume control enabled for client?'),
        ),
    ]
