# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0061_client_remote_volume_control_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvolumerequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
