# Generated by Django 3.2.5 on 2022-01-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmms', '0062_auto_20190625_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
